# -*- coding: utf-8 -*-
"""Uber Data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ez1so1k81gx2adDbl-XuxgTXOi43N0Oc
"""

import pandas as pd
import numpy as np
import datetime
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import calendar

data=pd.read_csv('/content/Uber Drives - .csv')
data.head()

data.isnull().any()

data.isnull().sum()

data=data.dropna()

data.isnull().sum()

data['START_DATE*'] = pd.to_datetime(data['START_DATE*'], format="%m/%d/%Y %H:%M")
data['END_DATE*'] = pd.to_datetime(data['END_DATE*'], format="%m/%d/%Y %H:%M")

hour=[]
day=[]
dayofweek=[]
month=[]
weekday=[]
for x in data['START_DATE*']:
    hour.append(x.hour)
    day.append(x.day)
    dayofweek.append(x.dayofweek)
    month.append(x.month)
    weekday.append(calendar.day_name[dayofweek[-1]])
data['HOUR']=hour
data['DAY']=day
data['DAY_OF_WEEK']=dayofweek
data['MONTH']=month
data['WEEKDAY']=weekday

data.head()

data['CATEGORY*'].value_counts()

sns.countplot(x='CATEGORY*',data=data)

data['MILES*'].plot.hist()

hours = data['START_DATE*'].dt.hour.value_counts()
hours.plot(kind='bar',color='red',figsize=(10,5))
plt.xlabel('Hours')
plt.ylabel('Frequency')
plt.title('Number of trips Vs hours')

data['PURPOSE*'].value_counts().plot(kind='bar',figsize=(10,5),color='brown')

data['WEEKDAY'].value_counts().plot(kind='bar',figsize=(10,5),color='blue')

data['DAY'].value_counts().plot(kind='bar',figsize=(10,5),color='green')

data['MONTH'].value_counts().plot(kind='bar',figsize=(10,5),color='black')

data['START*'].value_counts().plot(kind='bar',figsize=(25,10),color='blue')